# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: PrecheckJob
  pool: Azure Pipelines
  steps:
  - task: Bash@3
    name: precheckTask
    displayName: "preChecktask"
    inputs:
      targetType: 'inline'
      script: |
        set -e
        echo "##vso[task.setvariable variable=somename1;isOutput=true;]true"

- job: RunsOnServer
  dependsOn: [PrecheckJob]
  variables:
    somename1: $[ dependencies.PrecheckJob.outputs['somename1'] ]
  pool: Server
  condition: eq(dependencies.PrecheckJob.outputs['somename1'], 'true')
  steps:
  - task: Delay@1
    inputs:
      delayForMinutes: '10'

- job: PostcheckJob
  dependsOn: [PrecheckJob,RunsOnServer]
  pool: Azure Pipelines
  steps:
  - task: Bash@3
    name: postcheckTask
    displayName: "postChecktask"
    inputs:
      targetType: 'inline'
      script: |
        set -e
        echo "hello"
